# Generated by Django 4.2.5 on 2023-09-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
