# Generated by Django 4.2.5 on 2023-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking_booking_time_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(null=True, upload_to='doctors'),
        ),
    ]
