# Generated by Django 4.2.5 on 2023-10-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
