# Generated by Django 4.2.5 on 2023-10-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
